### ISSUE TITLE
Link dynamically with system-provided libsecp256k1 instead of bundling

### ISSUE THREAD

**Issue by jirutka** [rust-bitcoin/rust-secp256k1#629]
The secp256k1 readme says:

> If you want to compile this library without using the bundled symbols (which may be required for integration into other build systems), you can do so by adding --cfg=rust_secp_no_symbol_renaming' to your RUSTFLAGS variable.

The mentioned config option just disables symbols renaming, it doesn’t affect the build script. And the `links` attribute in `Cargo.toml` defines a non-standard name `rustsecp256k1_v0_8_1`. Should I build it with the following in `.cargo/config.toml` or how?

```toml
[target.<target>]
rustsecp256k1_v0_8_1 = { rustc-link-lib = "rustsecp256k1" }
```
